#
#   Copyright (c) 2008 João Abecasis
#
#   Distributed under the Boost Software License, Version 1.0. (See accompanying
#   file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

-include ../../config/make.cfg

SAGA_TEST_CACHE    = yes
SAGA_TEST_RUN      = ./run_adaptor_tests.sh
SAGA_DONT_INSTALL  = yes

include $(SAGA_MAKE_INCLUDE_ROOT)/saga.test.mk
